version: 2.1

jobs:
  build:

    macos:
      xcode: 11.0.0

    environment:
      SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/

    steps:
      - checkout
      - run: sudo xcode-select --switch /Library/Developer/CommandLineTools
      - run: sudo gem install cocoapods cocoapods-generate
      - run: cat $BASH_ENV
      - run: ./gradlew iosTest --info
